(function(){
  "use strict";
  var AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;
  var themes={
    station:{bpm:72,root:38,noise:.0035,cutoff:1050,wave:"triangle",progression:[0,-2,-5,-7],scale:[0,2,3,5,7,8,10],motif:[0,-1,2,-1,4,3,-1,1],pulse:[0,4,8,12],color:"枢纽潜行"},
    rain:{bpm:66,root:36,noise:.013,cutoff:1450,wave:"sine",progression:[0,-5,-2,-7],scale:[0,2,3,5,7,9,10],motif:[4,-1,-1,2,-1,5,-1,1],pulse:[0,6,8,14],color:"雨夜追踪"},
    hospital:{bpm:62,root:33,noise:.003,cutoff:900,wave:"sine",progression:[0,-1,-5,-3],scale:[0,1,3,5,7,8,10],motif:[0,-1,3,-1,-1,2,-1,5],pulse:[0,3,8,11],color:"无菌心跳"},
    harbor:{bpm:68,root:31,noise:.008,cutoff:820,wave:"triangle",progression:[0,-5,-7,-2],scale:[0,2,3,5,7,8,10],motif:[0,-1,4,-1,2,-1,5,3],pulse:[0,5,8,13],color:"黑潮暗涌"},
    train:{bpm:82,root:29,noise:.0045,cutoff:1200,wave:"sawtooth",progression:[0,-2,-5,-7],scale:[0,2,3,5,7,8,10],motif:[0,2,-1,3,4,-1,2,5],pulse:[0,2,4,6,8,10,12,14],color:"断轨追逐"},
    tower:{bpm:76,root:28,noise:.003,cutoff:1350,wave:"triangle",progression:[0,1,-5,-1],scale:[0,1,3,5,6,8,10],motif:[0,-1,6,5,-1,3,2,-1],pulse:[0,3,7,8,11,15],color:"零点终局"}
  };
  var scene=document.body.dataset.music||"station",theme=themes[scene]||themes.station;
  var ctx,master,musicBus,airBus,percBus,reverb,reverbGain,noiseSource,scheduler,nextStep=0,step=0,started=false,pausedByGame=false;
  var muted=localStorage.getItem("zero-hour-music-muted")==="1",button;
  function midi(n){return 440*Math.pow(2,(n-69)/12)}
  function style(){var s=document.createElement("style");s.textContent='.music-toggle{position:fixed;z-index:28;right:18px;top:62px;padding:5px 9px;border:1px solid rgba(210,230,225,.2);border-radius:2px;background:rgba(4,10,12,.88);color:#91a19d;font:8px ui-monospace,monospace;letter-spacing:.08em;cursor:pointer;backdrop-filter:blur(9px);box-shadow:0 7px 22px #0005}.music-toggle.on{color:#e5bd70;border-color:rgba(229,189,112,.48);box-shadow:0 0 18px rgba(229,189,112,.08)}@media(max-width:720px){.music-toggle{right:10px;top:47px;padding:4px 6px;font-size:7px}}';document.head.appendChild(s)}
  function label(){if(!button)return;button.textContent=started?(muted?"音乐：关":"音乐："+theme.color):(muted?"音乐：关":"点击开启音乐");button.classList.toggle("on",started&&!muted);button.setAttribute("aria-pressed",String(started&&!muted))}
  function impulse(){var len=Math.floor(ctx.sampleRate*1.7),b=ctx.createBuffer(2,len,ctx.sampleRate);for(var c=0;c<2;c++){var d=b.getChannelData(c);for(var i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,2.8)}return b}
  function tone(note,when,dur,gain,wave,bus,cutoff,attack){var o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=wave||"sine";o.frequency.setValueAtTime(midi(note),when);f.type="lowpass";f.frequency.setValueAtTime(cutoff||theme.cutoff,when);f.Q.value=.7;g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),when+(attack||.018));g.gain.exponentialRampToValueAtTime(.0001,when+dur);o.connect(f).connect(g).connect(bus||musicBus);if(reverb&&gain>.008)g.connect(reverb);o.start(when);o.stop(when+dur+.08)}
  function thump(when,gain,pitch){var o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.setValueAtTime(pitch||72,when);o.frequency.exponentialRampToValueAtTime(38,when+.18);g.gain.setValueAtTime(gain,when);g.gain.exponentialRampToValueAtTime(.0001,when+.24);o.connect(g).connect(percBus);o.start(when);o.stop(when+.26)}
  function click(when,gain,bright){var o=ctx.createOscillator(),g=ctx.createGain();o.type=bright?"square":"triangle";o.frequency.setValueAtTime(bright?1500:620,when);o.frequency.exponentialRampToValueAtTime(bright?480:180,when+.055);g.gain.setValueAtTime(gain,when);g.gain.exponentialRampToValueAtTime(.0001,when+.07);o.connect(g).connect(percBus);o.start(when);o.stop(when+.08)}
  function createNoise(){var frames=ctx.sampleRate*2,b=ctx.createBuffer(1,frames,ctx.sampleRate),d=b.getChannelData(0),last=0;for(var i=0;i<frames;i++){var white=Math.random()*2-1;last=.985*last+.015*white;d[i]=scene==="rain"?white*.55+last*.7:last*1.5}var src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=b;src.loop=true;filter.type=scene==="rain"?"highpass":"bandpass";filter.frequency.value=scene==="rain"?900:scene==="harbor"?240:420;filter.Q.value=scene==="rain"?.25:.7;g.gain.value=theme.noise;src.connect(filter).connect(g).connect(airBus);src.start();noiseSource=src}
  function remaining(){var el=document.getElementById("clock");if(!el)return 300;var m=(el.textContent||"").match(/(\d+):(\d+)/);return m?Number(m[1])*60+Number(m[2]):300}
  function tension(){var r=remaining();return r<=30?1:r<=60?.78:r<=120?.46:.18}
  function scheduleStep(when){var pos=step%16,bar=Math.floor(step/16),ten=tension(),root=theme.root+theme.progression[bar%theme.progression.length];
    if(pos===0){tone(root,when,4.6,.048,scene==="tower"?"sawtooth":"sine",musicBus,420,.65);tone(root+7,when+.06,4.3,.018,"triangle",musicBus,720,.75);tone(root+15,when+.13,4,.011,"sine",musicBus,1100,.8)}
    if(pos===0||pos===8)tone(root-12,when,.52,.038,theme.wave,musicBus,300,.012);
    if(theme.pulse.indexOf(pos)>=0){click(when,.009+ten*.011,ten>.7);if(scene==="hospital"&&(pos===0||pos===3))thump(when,.035+ten*.018,pos===0?76:61);if(scene==="train"&&pos%2===0)thump(when,.018+ten*.01,54)}
    if(pos%2===0){var degree=theme.motif[(pos/2+bar)%theme.motif.length];if(degree>=0){var n=root+24+theme.scale[degree%theme.scale.length];tone(n,when+.015,.28+ten*.12,.008+ten*.012,scene==="rain"?"sine":theme.wave,musicBus,theme.cutoff+ten*900,.012)}}
    if(ten>.7&&pos%2===1)click(when,.006+ten*.004,true);
    if(scene==="harbor"&&(pos===5||pos===13))tone(root+31,when,.13,.009,"square",percBus,680,.004);
    if(scene==="tower"&&(pos===7||pos===15))tone(root+36,when,.5,.011,"sine",musicBus,1800,.008);
    step++;
  }
  function runScheduler(){if(!ctx)return;while(nextStep<ctx.currentTime+.18){scheduleStep(nextStep);nextStep+=60/theme.bpm/4}}
  function begin(){if(started){if(ctx&&ctx.state==="suspended"&&!pausedByGame&&!muted)ctx.resume();return}started=true;ctx=new AudioCtx();master=ctx.createGain();musicBus=ctx.createGain();airBus=ctx.createGain();percBus=ctx.createGain();reverb=ctx.createConvolver();reverbGain=ctx.createGain();var comp=ctx.createDynamicsCompressor();reverb.buffer=impulse();master.gain.value=muted?0:.58;musicBus.gain.value=.75;airBus.gain.value=.8;percBus.gain.value=.72;reverbGain.gain.value=.16;musicBus.connect(master);airBus.connect(master);percBus.connect(master);reverb.connect(reverbGain).connect(master);master.connect(comp).connect(ctx.destination);createNoise();nextStep=ctx.currentTime+.08;scheduler=setInterval(runScheduler,90);runScheduler();if(pausedByGame)ctx.suspend();label()}
  function cue(kind){if(!started||muted||!ctx||pausedByGame)return;var now=ctx.currentTime+.01;if(kind==="dialog"){tone(theme.root+24+theme.scale[2],now,.12,.012,"sine",percBus,1600,.006);tone(theme.root+24+theme.scale[4],now+.07,.18,.009,"sine",percBus,1800,.006)}else if(kind==="clue"){tone(theme.root+24,now,.22,.015,"triangle",percBus,1800,.006);tone(theme.root+31,now+.1,.32,.012,"triangle",percBus,1900,.006)}else if(kind==="rewind"){tone(theme.root+31,now,.55,.018,"sine",percBus,1200,.01);tone(theme.root+19,now+.12,.65,.015,"sine",percBus,900,.01)}else if(kind==="event"){tone(theme.root+19,now,.16,.018,"triangle",percBus,1500,.006);tone(theme.root+24,now+.12,.32,.015,"sine",percBus,1250,.008);click(now+.04,.016,true)}}
  function pause(value){pausedByGame=!!value;if(!ctx)return;if(pausedByGame)ctx.suspend();else if(!muted)ctx.resume()}
  function toggle(){if(!started){muted=false;localStorage.setItem("zero-hour-music-muted","0");begin();return}muted=!muted;localStorage.setItem("zero-hour-music-muted",muted?"1":"0");master.gain.cancelScheduledValues(ctx.currentTime);master.gain.setTargetAtTime(muted?0:.58,ctx.currentTime,.08);label()}
  window.ZeroAudio={cue:cue,start:begin,pause:pause};style();button=document.createElement("button");button.className="music-toggle";button.type="button";button.setAttribute("aria-label","切换背景音乐");document.body.appendChild(button);button.addEventListener("pointerdown",function(e){e.stopPropagation();toggle()});document.addEventListener("pointerdown",function(){if(!started&&!muted)begin()},{once:true});document.addEventListener("keydown",function(){if(!started&&!muted)begin()},{once:true});document.addEventListener("visibilitychange",function(){if(!ctx)return;if(document.hidden)ctx.suspend();else if(!muted&&!pausedByGame)ctx.resume()});label();
})();
